- docs/sql-guide/operators/operators-home.md
changing operators based on feedback
> small updates based on feedback

- _config.yml
- _sass/color_schemes/featurebase.scss
- _sass/custom/custom.scss
These changes should make code snippets a bit more legible. Also enabled the copy-code button in JTD.
> Added constrast, larger text

- CNAME
- README.md
cname change to move docs.featurebase.com to this repo
> cname changes for migration

- docs/sql-guide/statements/statement-columns-show.md
https://molecula.atlassian.net/browse/FB-1938 got rid of internal type in show columns
> getting rid of internal types

- help-on-help/deployment-process
First draft for review :)
FYI, I'd prefer not to explicitly name us in the file, but it works as an interim step. Better (but for future-us to discuss) would be a GH user/administrator for the help or some way of firing off a notification to a slack channel (e.g., the docs-feedback team) ito notify us of an incoming PR request to merge with gh-pages (production)
> first draft of deployment process

- _config.yml
- _includes/com-config/com-config-flags-backup-restore-common.md
- _includes/com-config/com-config-flags-backup-restore-tls.md
- _includes/community/com-issue-mac-gatekeeper-source.md
- _includes/contact-support.md
- _includes/footer_custom.html
- docs/cloud/cloud-databases/cloud-db-states.md
- docs/community/com-config/com-config-cli-enable-sql-endpoint.md
- docs/community/com-config/com-config-home.md
- docs/community/com-startup-connect.md
- index.md
Changes to docs from discussion with @kordless on 2023-02-23
* Updated page footer to include methods of getting in contact -- Discord, raise GH issue for help, contact on fb.com form
* Fixed the homepage to make setup/install clearer
* SQL endpoint help revised to make clearer what's actually on offer
* Community startup updated to turn on sql endpoint
* Added GH link to topnav for featurebase-docs
* broken link fixes too
Note there are a bunch of commented out content which will be enabled after the Community config authentication is merged in
> Kord changes

- _includes/sql-guide/summary-constraints-datatypes.md
- _includes/sql-guide/table_create_eg_all_datatypes.md
- _includes/sql-guide/timestamp-timeunit-table.md
- docs/sql-guide/data-types/data-type-timestamp.md
- docs/sql-guide/functions/function-format.md
- docs/sql-guide/functions/function-totimestamp.md
This PR updates documentation for work done for FB-1968.
> Documentation for fb-1968

- _includes/cloud-db/cloud-summary-db-version.md
- _includes/contact-support.md
- docs/cloud/cloud-databases/cloud-db-manage.md
- docs/cloud/cloud-databases/cloud-db-versions.md
- docs/cloud/cloud-troubleshooting/issue-cloud-version-unknown.md
Ticket 1188
https://molecula.atlassian.net/browse/CLOUD-1188?atlOrigin=eyJpIjoiN2I2MjdkZGRlMjZlNDJiZmJmNDg5OGE2ZWVkMDYwODgiLCJwIjoiaiJ9
> Main compared to gh-pages ready for push to prod (#47)

- _includes/sql-guide/datetimeadd-function-timeunit-table.md
- docs/sql-guide/functions/function-datetimeadd.md
- docs/sql-guide/sql-guide-home.md
Also a minor correction related to the deprecated sql endpoint flag.
> Adding documentation for FB-1893.

- _includes/cloud-db/cloud-summary-db-disk-utilization.md
- docs/cloud/cloud-databases/cloud-db-delete.md
- docs/cloud/cloud-databases/cloud-db-disk-utilization.md
- docs/cloud/cloud-databases/cloud-db-manage.md
- docs/cloud/cloud-databases/cloud-db-states.md
- docs/cloud/cloud-databases/cloud-db-versions.md
https://molecula.atlassian.net/browse/CLOUD-1179
> CLOUD-1179 - Added docs for 'Disk Utilization'

- _includes/cloud-db/cloud-summary-db-disk-utilization.md
- docs/cloud/cloud-databases/cloud-db-delete.md
- docs/cloud/cloud-databases/cloud-db-disk-utilization.md
- docs/cloud/cloud-databases/cloud-db-manage.md
- docs/cloud/cloud-databases/cloud-db-states.md
- docs/cloud/cloud-databases/cloud-db-versions.md
https://molecula.atlassian.net/browse/CLOUD-1179
> gh pages CLOUD-1179 - Added docs for 'Disk Utilization' (#67)

- _includes/cloud-db/cloud-db-backup.md
- _includes/cloud-db/cloud-db-upgrade-version.md
- _includes/cloud-db/cloud-summary-db-version.md
- docs/cloud/cloud-databases/cloud-db-manage.md
- docs/cloud/cloud-databases/cloud-db-versions.md
Adding more version information
Adding backup information
> minor updates to db manage

- _includes/components/aux_nav.html
- _includes/components/breadcrumbs.html
- _includes/components/children_nav.html
- _includes/components/footer.html
- _includes/components/header.html
- _includes/components/mermaid.html
- _includes/components/search_footer.html
- _includes/components/search_header.html
- _includes/components/sidebar.html
- _includes/head_custom.html
- _includes/icons/code_copy.html
- _includes/icons/document.html
- _includes/icons/expand.html
- _includes/icons/external_link.html
- _includes/icons/icons.html
- _includes/icons/link.html
- _includes/icons/menu.html
- _includes/icons/search.html
- _layouts/default.html
- docs/tools/tools-home.md
@ljsinclair this was in our previous docs. Without it, we don't have tracking on docs. We need to address this, so please take a look. it's unclear to me why don't have and of the _layouts or certain things, so I added what was necessary from the JTD repo.
> adding google tag

- _includes/com-install/com-install-setup-install-dir.md
This was my mistake and brought up by Vivian.
One line fix in this branch which shouldn't cause any other problems :)
> Community install guide fix

- help-on-help/style-guide/content-nav-nesting-folder.md
- help-on-help/style-guide/page-purpose-layout.md
changed index file extension which was wrong
> fixed incorrect file extension for index

- help-on-help/publishing-workflow/README.md
@ljsinclair updated process as discussed
> updates to release process

- _includes/head_custom.html
- _sass/custom/custom.scss
- assets/js/code-copy.js
Added a copy button to code blocks. Tried to isolate it so we can find and remove it later if we update jtd.
> Added code copy button

- docs/sql-guide/system-tables/system-tables-home.md
Based on our convo with Zappi, adding context to sys table docs
> update to sys table info

- _includes/cloud-query/cloud-before-query.md
- _includes/cloud-query/cloud-query-choose-db.md
- _includes/cloud-query/cloud-query-execute.md
- _includes/cloud-query/cloud-query-open-history.md
- _includes/cloud-query/cloud-query-open-schema-browser.md
- docs/cloud/cloud-query/cloud-query-data.md
- docs/cloud/cloud-query/cloud-query-execute.md
- docs/cloud/cloud-query/cloud-query-history.md
- docs/cloud/cloud-query/cloud-query-results.md
- docs/cloud/cloud-query/cloud-query-schema-browser.md
@ljsinclair another iteration that will just merge in if not review by tomorrow. Getting closer to done though
> adding schema and history pages

- Gemfile.lock
- docs/sql-guide/functions/function-ascii.md
- docs/sql-guide/functions/function-charindex.md
Added info about ASCII() used charset and the limits upon it.
Added info about CHARINDEX() return values
> Additional details found from test backfill

- docs/concepts/overview-bitmap-data.md
- help-on-help/README.md
Minor fixes, some duplicates removed
> Remove duplicate text

- docs/community/com-api/old-apis.md
- docs/community/com-api/old-http-endpoint.md
- docs/community/com-config/old-scaling.md
- docs/community/com-monitoring/old-monitoring.md
- docs/community/old-setup/old-getting-started.md
- docs/pql-guide/pql-read-row.md
- docs/pql-guide/pql-write-set.md
- old-backup/old-ingesters.md
builds and tested with no broken links
> fixed broken link to old-ingesters.md

- _includes/sql-guide/mutex_updates.md
- _includes/sql-guide/set_updates.md
- _includes/sql-guide/timequantum_updates.md
- docs/sql-guide/data-types/data-type-bool.md
- docs/sql-guide/data-types/data-type-decimal.md
- docs/sql-guide/data-types/data-type-id.md
- docs/sql-guide/data-types/data-type-idset.md
- docs/sql-guide/data-types/data-type-idsetq.md
- docs/sql-guide/data-types/data-type-int.md
- docs/sql-guide/data-types/data-type-string.md
- docs/sql-guide/data-types/data-type-stringset.md
- docs/sql-guide/data-types/data-type-stringsetq.md
- docs/sql-guide/data-types/data-type-timestamp.md
- docs/tools/fbsql/fbsql-home.md
fbsql api key functionality
update behavior for datatypes
> null updates and api key

- _includes/sql-guide/query-status.md
- assets/images/sql-guide/kill_query_stmt.svg
- docs/sql-guide/statements/statement-kill-query.md
- docs/sql-guide/statements/statements-home.md
- docs/sql-guide/system-tables/system-tables-home.md
- help-on-help/regenerate-sql-svg/sql3.ebnf
As you review, please feel free to make corrections and push.
> Documentation for the new kill query statement

- _includes/tools-python/python-release-note.md
- docs/tools/python-client-library/python-client-install.md
- docs/tools/python-client-library/python-client-library-home.md
- docs/tools/tools-home.md
As you review please feel free to make corrections and push. Thanks.
> Adding documentation for python client library

- _includes/sql-guide/create-table-segments.md
> moved table back into sql because breaks in markdown

- docs/concepts/WIP-data-modeling
forgot to explicitly remove the page from navigation which avoids it appearing at bottom of nav with no content
> excluding the page from nav

- _includes/com-backup/com-config-flags-backup-restore-common.md
- docs/community/com-backup/com-config-backup.md
- docs/community/com-backup/com-config-restore.md
adding docs for the tar option for backup and restore
> tar file docs

- docs/concepts/time-quantums.md
> removing the comment

- docs/tools/python-client-library/python-client-install.md
- docs/tools/python-client-library/python-client-library-home.md
- Removed the references to the release site and install from binary steps.
- Added instructions to install from source and added links to the source public repo
Please feel free to correct and commit. Thanks!
> Python client public repo updates

- _sass/custom/custom.scss
made h4 a bit bigger so its not smaller than body text
> Css h4 fix

- docs/sql-guide/operators/operators-home.md
`Operator` page under `SQL Guide` has been updated to include `<>` as Not Equal operator.
> Updated docs to include <> as not equal operator

- _includes/cloud-auth/cloud-auth-click-create.md
- _includes/cloud-auth/cloud-auth-new-key.md
- _includes/cloud-auth/cloud-auth-revoke-warning.md
- docs/cloud/cloud-authentication/cloud-auth-create-key.md
- docs/cloud/cloud-authentication/cloud-auth-manage.md
- docs/cloud/cloud-authentication/cloud-auth-rename-key.md
- docs/cloud/cloud-authentication/cloud-auth-revoke-key.md
- docs/cloud/cloud-configuration/configuration-home.md
- docs/cloud/cloud-databases/cloud-db-delete.md
- docs/cloud/cloud-databases/cloud-db-manage.md
- docs/cloud/cloud-ingest/cloud-ingest-manage.md
- docs/cloud/cloud-org/cloud-org-manage.md
- docs/cloud/cloud-query/cloud-query-data.md
- docs/cloud/cloud-tables/cloud-table-manage.md
- docs/cloud/cloud-troubleshooting/cloud-troubleshooting-home.md
- docs/cloud/cloud-users/cloud-users-manage.md
- docs/cloud/my-account/cloud-account-manage.md
- docs/cloud/programmaticaccess.md
Adds documentation for how to use the new API key stuff in the UI. Also fixes the ordering for some of the items listed in the docs.
> Added "Manage API Keys" tab under cloud

- docs/community/com-ingest/com-ingest-source-sql.md
> removed note to self

- _includes/sql-guide/table_create_eg_all_datatypes.md
- docs/concepts/concept-ingest-eg-large-dataset.md
- docs/sql-guide/statements/statement-table-create.md
FeatureBase updated its comment syntax to be `with comment` instead of just `comment`. Update the documentation to reflect that change.
> CLOUD-1620 Update documentation with new WITH COMMENT syntax

- docs/community/com-ingest/com-ingest-flags-kafka-static.md
- docs/tools/python-client-library/python-client-library-home.md
Add the new DLQ flags to Kafka static consumer flag list.  
Minor updates to Python client api documentation.
> Add the new DLQ flags to Kafka static consumer flag list. 

- docs/sql-guide/statements/statement-insert-bulk.md
- docs/tools/fbsql/fbsql-running-sql.md
This is the final step of the STREAM -> INLINE transition.
> Rename STREAMX to STREAM

- docs/cloud/cloud-home.md
- docs/tools/python-client-library/python-client-example.md
- docs/tools/python-client-library/python-client-install.md
- docs/tools/python-client-library/python-client-library-home.md
- docs/tools/tools-home.md
> General fixes

- _includes/sql-guide/datatype-mapping.md
- _includes/sql-guide/sql-datatypes.md
- _includes/sql-guide/table-create-types-all-eg.md
- docs/sql-guide/data-types/data-type-vector.md
Add vector a few places and CAPS it for display in nav list.
> Vector diff

- docs/sql-guide/statements/statement-insert-bulk.md
I haven't built this and looked at it in rendered form. Couldn't remember how to do it and didn't see instructions.
> add docs for concurrency and multi-url on bulk insert

- _includes/sql-guide/insert-bulk-transform-tuple-eg.md
fixed code block for tuple function and bulk insert statement
> fixed leading code block shortcode

- _includes/cloud-db/cloud-db-backup.md
- _includes/cloud-db/cloud-db-upgrade-version.md
- _includes/contact-support.md
- _includes/footer_custom.html
- docs/cloud/cloud-databases/cloud-db-states.md
- docs/community/old-setup/old-community-quickstart-guide.md
discord signup link fix as advised by @kordless in Slack
> fixed dodgy discord signup link

- docs/cloud/cloud-home.md
- docs/concepts/concept-examples.md
- docs/sql-guide/statements/statement-insert-bulk-csv-example.md
- docs/sql-guide/statements/statement-insert-bulk-ndjson-example.md
- docs/sql-guide/statements/statement-insert-bulk-orc-example.md
- docs/sql-guide/statements/statement-insert-bulk-parquet-example.md
- docs/sql-guide/statements/statement-insert-bulk.md
- docs/sql-guide/statements/statements-home.md
This PR is to add documentation for ORC file support for Bulk Insert in SQL3
> Documentation for ORC File support for Bulk Insert

- docs/community/com-ingest/com-ingest-example-kafka-avro.md
- docs/community/com-ingest/com-ingest-source-kafka-avro.md
This PR updates Kafka consumer documentation for Storage Specifier usage.
> Update Kafka consumer documentation for Storage Specifier usage

- _config.yml
shifted out of kord cookbook to reduce changes
> moved callout here

- _includes/cloud-db/serverless-preview-warning.md
> missing include found and added

- help-on-help/style-guide/standard-terms.md
> Help on help updates

- _includes/com-ingest/com-ingest-flag-csv.md
Error in docs found by customer fixed in this PR
https://discord.com/channels/997235309131595786/1169055849415704627
> error in docs mentioned in discord support

- docs/sql-guide/statements/statement-explain.md
EXPLAIN discovered in Discord Support channel
https://discord.com/channels/997235309131595786/1141380361528557730
Tested and works on FB Cloud
> Added EXPLAIN statement found in discord support channel

- docs/pql-guide/pql-read-unionrows.md
User reported error in PQL Unionrows -- https://discord.com/channels/997235309131595786/1017121543861583873/1185179522576945162
Fixed and awaiting review
> updated as per discord report

- docs/cloud/cloud-databases/cloud-db-create-custom.md
- docs/cloud/cloud-databases/cloud-db-delete.md
> Main build fix

- docs/tools/python-client-library/python-client-example.md
discovered error in sql example to blame for jira FB-2452
This has now been fixed
> updated as per jira comment

- docs/cloud/my-account/cloud-user-move.md
Like it says on the box, this page has an updated summary based on Pat comments.
Note, invitation for new user (as-in not already existing within FeatureBase) is handled in a separate page
> updated summary based on Pat comments on CLOUD-1803

- _includes/cloud-db/cloud-db-vendors.md
- docs/cloud/cloud-databases/cloud-db-create-custom.md
- docs/cloud/cloud-databases/cloud-db-manage.md
This update was made because of the Azure announcement on the FeatureBase website
https://www.featurebase.com/blog/multi-cloud-support-microsoft-azure
The content was copied from the following sections and may need clarification and updating:
* Key differences of FeatureBase Azure vs FeatureBase AWS
* Meeting compliance... the second paragraph starting with "...The standard configuration..."
Please check this PR for accuracy, **especially** for AWS for which I've got no information
**NOTE** At time of writing (2024-01-16), Azure is not available in FeatureBase Cloud. I expect this will change in the near future.
> updated from the blog post, but needs review to ensure accuracy

- _includes/sql-guide/max-val-string-varchar.md
- _includes/sql-guide/unique-id-string-warning.md
- docs/sql-guide/data-types/data-type-string.md
- docs/sql-guide/data-types/data-type-varchar.md
- docs/sql-guide/data-types/data-type-vector.md
- docs/sql-guide/data-types/data-types-home.md
- docs/sql-guide/sql-guide-home.md
- docs/sql-guide/statements/statement-table-create-show.md
- docs/sql-guide/statements/statement-view-create.md
Documentation based on "storage types currently" listed in https://molecula.atlassian.net/wiki/spaces/EN/pages/1216020481/Data+Types
SQL runs successfully in FeatureBase Cloud as of 2024-02-14
Additional detail should be added by the reviewer if required
> first draft VARCHAR datatype doc

- _includes/python-lib/python-lib-connect-db-links.md
- docs/tools/python-client-library/python-client-install.md
- docs/tools/python-client-library/python-client-query.md
cleanup from removing community help missed at the time
> small fixes to remove include from earlier version

- help-on-help/writing-help/writing-bans.md
- help-on-help/writing-help/writing-rules.md
update to add image issues and pull out text issues into same page
> revised and fixed

- docs/cloud/cloud-org/cloud-org-id.md
- docs/cloud/cloud-org/cloud-org-manage.md
New page added that will be useful for users who are seeking support
> Organization ID page

- Gemfile.lock
- docs/tools/fbsql-examples/fbsql-loader-eg-kafka-source.md
- docs/tools/fbsql/fbsql-loader-toml-config.md
Please feel free to fix issues as needed. Thanks.
> Update documentation describing time quantum support added to fbsql kafka loader.
